name: test
on: 
  pull_request: 
    branches:
      - "**"
jobs:
  test: 
    name: first test github action
    runs-on: ubuntu-latest
    steps:
      - name: checkout the Repo # Basically mean that github will clone my repo on their machine
        uses: action/checkout@v3
      
      - name: install dependencies 
        run: npm install

      - name: build typescripts file
        run: npm run build