name: testing lint, pritter and unit tests
on: [push]

jobs: 
    checks:
        name: checking linting & formatting
        runs-on: ubuntu-latest
        steps: 
            - name: checkout the repo
              uses: actions/checkout@v3

            - name: setting node enviornment
              uses: actions/setup-node@v4

            - name: installing dependencies
              run: npm install
              working-directory: Second
            
            - name: checking linting
              run: npm run lint:check
              working-directory: Second

            - name: checking formatting
              run: npm run format:check
              working-directory: Second
    
    testing:
        name: testing unit testing
        runs-on: ubuntu-latest
        steps: 
            - name: checkout the repo
              uses: actions/checkout@v3

            - name: setting node enviornment
              uses: actions/setup-node@v4

            - name: installing dependencies
              run: npm install
              working-directory: Second
            
            - name: checking linting
              run: | 
                npm run test
                echo "Test completed"  
              working-directory: Second